<header id="area-header" class="w-100 --box">
    <div class="container kit-box rounded-4">
        <button class="--btn-left btn btn-dark rounded-circle">
            <i class="bi bi-arrow-left"></i>
        </button>
        <div class="hero-info row">
            <div class="col-lg-6 kit-box p-3">
                <div class="p-3">
                    <p>Super promoção</p>
                    <h1 class="text-uppercase text-primary">Cadeira Gamer RTX</h1>
                    <p>
                        Lorem ipsum dolor sit amet 
                        consectetur adipisicing elit. 
                        Possimus, et minus sed illum 
                        nisi accusamus sit quod eveniet 
                        omnis.
                    </p>
                    <button class="btn btn-primary">
                        Carrinho
                        <i class="bi bi-cart ms-1"></i>
                    </button>
                </div>
            </div>
            <div class="container-product-image col-lg-6 kit-box p-3">
                <img class="--product-image" src="./src/assets/products/cadeira.png" alt="cadeira gamer preta">               
            </div>
        </div>
        <button class="--btn-right btn btn-dark rounded-circle">
            <i class="bi bi-arrow-right"></i>
        </button>
    </div>
</header>
<main class="w-100 kit-box flex-column">
    <section id="area-categorys" class="container mt-3 p-3">
        <h2>Top Categorias</h2>
        <div class="w-100 kit-box p-3">
            <button class="btn btn-secondary rounded-circle">
                <i class="bi bi-arrow-left"></i>
            </button>
            <ul class="list-inline w-100 kit-box m-0">
                <li>
                    <div class="--card kit-box flex-column rounded-4 border kit-gradient-bg-secondary">
                        <img src="./src/assets/products/cadeira.png" alt="foto-da-categoria">     
                        <p>Informática</p>
                    </div>
                </li>
                <li>
                    <div class="--card kit-box flex-column rounded-4 border kit-gradient-bg-secondary">
                        <img src="./src/assets/products/cadeira.png" alt="foto-da-categoria">     
                        <p>Informática</p>
                    </div>
                </li>
            </ul>
            <button class="btn btn-secondary rounded-circle">
                <i class="bi bi-arrow-right"></i>
            </button>
        </div>
    </section>
    <section id="area-products" class="container kit-box flex-column mt-3">
        <h2>Produtos em alta</h2>
        <ul class="list-inline w-100 row m-0 mt-3">
            <li class="col-lg-4 kit-box p-1">
                <div class="--card rounded-4 border kit-gradient-bg-secondary">
                    <img src="./src/assets/products/cadeira.png" alt="imagem do produto">
                    <div class="w-100 p-3">
                        <h6>Cadeira gamer XTR</h6>
                        <p>R$ 450,00</p>
                        <button class="w-100 btn btn-secondary">Por no Carrinho <i class="bi bi-cart"></i></button>
                    </div>
                    <button class="--btn-heart btn btn-danger">
                        <i class="bi bi-heart"></i>
                    </button>
                </div>
            </li>
            <li class="col-lg-4 kit-box p-1">
                <div class="--card rounded-4 border kit-gradient-bg-secondary">
                    <img src="./src/assets/products/monitor.png" alt="imagem do produto">
                    <div class="w-100 p-3">
                        <h6>Cadeira gamer XTR</h6>
                        <p>R$ 450,00</p>
                        <button class="w-100 btn btn-secondary">Por no Carrinho <i class="bi bi-cart"></i></button>
                    </div>
                    <button class="--btn-heart btn btn-secondary">
                        <i class="bi bi-heart"></i>
                    </button>
                </div>
            </li>
        </ul>
    </section>
</main>