<main class="w-100 kit-box flex-column">
    <section class="w-100 kit-box">
        <div class="container kit-box">
            <div class="w-100 row">
                <div class="col-lg-6 kit-box flex-column border-end p-3">
                    <img class="--logo" src="./src/assets/system/logo.png" alt="foto da logo do site">
                    <h1 class="text-uppercase">Crie sua conta</h1>
                    <p class="mt-3">Vai ser rapidinho !</p>
                </div>
                <form class="col-lg-6 kit-box p-3">
                    <div>
                        <div class="mb-3">
                            <label for="user" class="form-label">Nome completo:</label>
                            <input id="email" name="email" type="text" class="form-control form-control-lg" placeholder="digite seu nome completo">
                        </div>
                        <div class="mb-3">
                            <label for="user" class="form-label">E-mail:</label>
                            <input id="email" name="email" type="text" class="form-control form-control-lg" placeholder="digite seu e-mail">
                        </div>
                        <div class="mb-3">
                            <label for="user" class="form-label">Senha:</label>
                            <input id="password" name="password" type="password" class="form-control form-control-lg" placeholder="digite sua senha">
                        </div>
                        <div class="mb-3">
                            <label for="user" class="form-label">Confirme a Senha:</label>
                            <input id="password" name="password" type="password" class="form-control form-control-lg" placeholder="confirme sua senha">
                        </div>
                        <div class="mb-3">
                            <label>Mostrar Senha</label>
                            <input id="showPassword" type="checkbox">
                        </div>
                        <button class="w-100 btn btn-primary">Criar Conta <i class="bi bi-arrow-right"></i></button>
                        <p class="mt-5">Já tem uma conta ? <a class="text-primary" href="login">Entrar</a></p>
                    </div>
                </form>
            </div>
        </div>
    </section>
</main>