<header class="container kit-box justify-content-start border-top pt-3">
    <a class="btn btn-secondary btn-sm rounded-circle">
        <i class="bi bi-arrow-left"></i>
    </a>
    <h1 class="m-0 ms-3">Perfil</h1>
</header>
<main class="w-100 kit-box flex-column">
    <section id="area-profile" class="w-100 kit-box flex-column">
        <div class="container kit-box">
            <div class="row w-100">
                <div class="col-lg-8 kit-box p-3">
                    <div class="w-100 kit-mw-sm">
                        <h2>Vinicius Miranda</h2>
                        <p class="mt-3">
                            Lorem ipsum dolor sit, 
                            amet consectetur adipisicing elit. 
                            Provident nesciunt aspernatur sapiente veritatis 
                        </p>
                        <div class="w-100 kit-box flex-column align-items-start mt-5">
                            <h5>Editar Perfil</h5>
                            <div class="w-100 kit-box justify-content-start mt-3">
                                <button class="btn btn-dark border">Conta <i class="bi bi-pencil ms-2"></i></button>
                                <button class="btn btn-dark border mx-1">Pessoal <i class="bi bi-pencil ms-2"></i></button>
                                <button class="btn btn-dark border">Endereço <i class="bi bi-pencil ms-2"></i></button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 kit-box flex-column p-3">
                    <div class="--card-avatar kit-box mb-3">
                        <img class="--avatar border shadow" src="./src/assets/users/vini.jpg" alt="foto de perfil do usuário">
                        <i class="bi bi-upload fs-1"></i>
                        <input id="avatar" name="avatar" type="file">
                    </div>
                    <div class="w-100 kit-box">
                        <button class="btn btn-primary">Salvar <i class="bi bi-save"></i></button>
                        <button class="btn btn-outline-danger ms-2"><i class="bi bi-x"></i></button>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>
<?php 
    require_once '../app/views/layouts/form-account.phtml'
?>
<?php 
    require_once '../app/views/layouts/form-personal.phtml'
?>