<footer id="area-footer" class="w-100 kit-box kit-gradient-bg-secondary mt-5">
    <div class="container kit-box flex-column p-1 pb-3">
        <div class="w-100 row">
            <div class="col-lg-4 p-1">
                <img class="--logo" src="./src/assets/system/logo.png" alt="foto da logo">
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
                <ul class="--network list-inline w-100 kit-box justify-content-start">
                    <li>
                        <a>
                            <i class="bi bi-instagram"></i>
                        </a>
                    </li>
                    <li>
                        <a>
                            <i class="bi bi-facebook"></i>
                        </a>
                    </li>
                    <li>
                        <a>
                            <i class="bi bi-youtube"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="w-100 border-top pt-5">
            <p>@ 2025 - TudoMix - Criado por Vinicius Miranda.</p>
        </div>
    </div>
</footer>