<div class="kit-modal">
    <form class="kit-mw-md --window kit-gradient-bg-secondary">
        <div class="--header">
            <h5 class="--title">Editando Conta</h5>
        </div>
        <div class="--body row my-3">
            <div class="col-lg-6 p-1">
                <label class="form-label">ID</label>
                <input class="form-control" type="text" value="#2620" placeholder="id" disabled>
            </div>
            <div class="col-lg-6 p-1">
                <label class="form-label">Email</label>
                <input class="form-control" type="text" value="#2620" placeholder="id" disabled>
            </div>
            <div class="col-lg-6 mt-3 p-1">
                <label class="form-label">Senha</label>
                <div class="w-100 kit-box">
                    <input class="form-control" type="password" value="30506040" placeholder="senha" disabled>
                    <button class="btn btn-outline-secondary ms-1"><i class="bi bi-pencil"></i></button>
                </div>
            </div>
        </div>
        <div class="--footer">
            <button class="btn btn-danger ms-2">Fechar <i class="ms-1 bi bi-x"></i></button>
        </div>  
    </form>
</div>