<div id="form-cart" class="kit-modal d-flex">
    <form class="--window kit-mw-sm kit-gradient-bg-secondary">
        <div class="--header kit-box">
            <button class="btn btn-secondary rounded-circle me-3">
                <i class="bi bi-arrow-left"></i>
            </button>
            <h5 class="--title"><i class="bi bi-cart"></i> Carrinho <span>5</span></h5>
        </div>
        <div class="--body">
            <ul class="list-inline">
                <li>
                    <div class="--card">
                        <div>
                            <img class="" src="" alt="">
                        </div>
                    </div>
                </li>
            </ul>
        </div>
        <div class="--footer">
            <button class="btn btn-primary w-100">
                Finalizar
                <i class="bi bi-check ms-1"></i>
            </button>
        </div>
    </form>
</div>