<div class="kit-modal">
    <form class="--window kit-mw-md kit-gradient-bg-secondary">
        <div class="--header">
            <h5>Editando informações pessoal</h5>
        </div>
        <div class="--body row my-3">
            <div class="col-lg-12 mb-3 p-1">
                <label for="" class="form-label">Nome completo</label>
                <input type="text" class="form-control" placeholder="nome completo">
            </div>
        </div>
        <div class="--footer">
            <button class="btn btn-primary">
                Salvar <i class="bi bi-save"></i>
            </button>
            <button class="btn btn-outline-danger ms-2"><i class="bi bi-x"></i></button>
        </div>
    </form>
</div>