<div id="form-cart" class="kit-modal">
    <form class="--window kit-mw-sm kit-gradient-bg-secondary justify-content-start">
        <div class="--header kit-box justify-content-start">
            <button class="btn btn-secondary rounded-circle me-3">
                <i class="bi bi-arrow-left"></i>
            </button>
            <h5 class="--title"><i class="bi bi-cart"></i> Carrinho <span>5</span></h5>
        </div>
        <div class="--body my-3">
            <div class="w-100 text-end">
                <h6 class="fs-4">Subtotal</h6>
                <p class="fs-3 text-success">R$ 350,00</p>
            </div>
            <ul class="list-inline">
                <li class="w-100 container-fluid">
                    <div class="w-100 row">
                        <div class="col-auto kit-box p-3">
                            <img class="--image-product" src="./src/assets/products/monitor.png" alt="foto do produto">
                        </div>
                        <div class="col kit-box justify-content-start p-3">
                            <div>
                                <h6>Monitor ultra watch</h6>
                                <p>R$ 25,00</p>
                            </div>
                        </div>
                    </div>
                    <div class="w-100 row">
                        <div class="col kit-box justify-content-start">
                            <div class="kit-box bg-dark border rounded-4 px-3 py-2">
                                <button class="btn btn-secondary btn-sm">
                                    <i class="bi bi-dash"></i>
                                </button>
                                <p class="m-0 mx-3">30</p>
                                <button class="btn btn-secondary btn-sm">
                                    <i class="bi bi-plus"></i>
                                </button>
                            </div>
                        </div>
                        <div class="col-auto kit-box">
                            <button class="btn btn-outline-danger btn-sm">
                                Deletar <i class="bi bi-trash"></i>
                            </button>
                        </div>
                    </div>
                </li>
                <li class="w-100 container-fluid mt-3">
                    <div class="w-100 row">
                        <div class="col-auto kit-box p-3">
                            <img class="--image-product" src="./src/assets/products/cadeira.png" alt="foto do produto">
                        </div>
                        <div class="col kit-box justify-content-start p-3">
                            <div>
                                <h6>Monitor ultra watch</h6>
                                <p>R$ 25,00</p>
                            </div>
                        </div>
                    </div>
                    <div class="w-100 row">
                        <div class="col kit-box justify-content-start">
                            <div class="kit-box bg-dark border rounded-4 px-3 py-2">
                                <button class="btn btn-secondary btn-sm">
                                    <i class="bi bi-dash"></i>
                                </button>
                                <p class="m-0 mx-3">30</p>
                                <button class="btn btn-secondary btn-sm">
                                    <i class="bi bi-plus"></i>
                                </button>
                            </div>
                        </div>
                        <div class="col-auto kit-box">
                            <button class="btn btn-outline-danger btn-sm">
                                Deletar <i class="bi bi-trash"></i>
                            </button>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
        <div class="--footer">
            <button class="btn btn-primary w-100">
                Finalizar
                <i class="bi bi-check ms-1"></i>
            </button>
        </div>
    </form>
</div>