<nav id="navigation" class="w-100 kit-box flex-column">
    <div class="--top w-100 kit-box kit-gradient-bg-secondary p-1">
        <div class="container kit-box justify-content-between">
            <a>
                <img class="--logo" src="./src/assets/system/logo.png" alt="logo da loja">
            </a>
            <form class="kit-box">
                <input id="navigation-search" name="search" type="text" class="form-control" placeholder="O que está procurando ?">
                <button class="btn btn-primary btn-sm ms-1">
                    <i class="bi bi-search"></i>
                </button>
            </form>
            <div class="--action">
                <button class="btn btn-dark">
                    <i class="bi bi-cart"></i>
                    <span>Carrinho</span>
                    <span class="text-primary">
                        3
                    </span>
                </button>
                <a class="btn btn-dark">
                    <i class="bi bi-heart"></i>
                </a>
                <a class="btn btn-dark">
                    <i class="bi bi-person"></i>
                </a>
            </div>
        </div>
    </div>
    <div class="--bottom w-100 kit-box px-1 py-3">
        <div class="container kit-box justify-content-between">
            <div class="kit-box">
                <button class="btn btn-dark bg-black">
                    <i class="bi bi-list"></i>
                    Categorias
                </button>
                <ul class="list-inline kit-box m-0 ms-3">
                    <li><a>Home</a></li>
                    <li><a class="active mx-4">Produtos</a></li>
                    <li><a>Sobre</a></li>
                </ul>
            </div>
            <div class="kit-box">
                <h6 class="m-0">Contato:</h6>
                <p class="m-0 ms-2">(27) 99643-5864</p>
            </div>
        </div>
    </div>
</nav>